# ================================================
# Kubernetes Manifest for the Nextcloud Project
# Author   : Lumitek
# Date     : 2025-08-15
# Description:
#   This manifest contains the following configurations:
#   - The Redis Service
# ================================================
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
    - port: "${REDIS_SVC_PORT}"
      targetPort: "${REDIS_PORT}"
      protocol: TCP
---