# ================================================
# Kubernetes Manifest for the Nextcloud Project
# Author   : Lumitek
# Date     : 2025-08-15
# Description:
#   This manifest contains the following configurations:
#   - The Argo CD Nextcloud Devnet Application (devnet)
#   - Activated SyncPolicy
# ================================================
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-devnet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "${GIT_REPO}"
    path: k8s/overlays/devnet # repository inside the project where are manifests
    targetRevision: devnet # Git branch to deploy
  destination:
    server: "${KUBERNETES_SERVER}"
    namespace: "${DEVNET}"
  syncPolicy:
    automated: 
      selfHeal: true # Argo cd keeps the cluster always in sync with the source
      prune: true # Delete objects what are not part of the new git version
---