# ================================================
# Kubernetes Manifest for the Nextcloud Project
# Author   : Lumitek
# Date     : 2025-08-15
# Description:
#   This manifest contains the following configurations:
#   - Headless Service to be used with the DNS record
# ================================================
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: "${MARIADB_SVC_PORT}"
    name: mariadb-port
  clusterIP: None
---