# ================================================
# Kubernetes Manifest for the Nextcloud Project
# Author   : Lumitek
# Date     : 2025-08-15
# Description:
#   This manifest contains the following configurations:
#   - The PHP-FPM Service
# ================================================
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: ClusterIP
  ports:
    - port: "${PHP_SVC_PORT}"
      targetPort: "${PHP_CONTAINER_PORT}"
      protocol: TCP
---